name: Default

on: [push]

jobs:
  default:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: { node-version: "${{ matrix.node }}" }
      - run: npm install
      - run: npm run lint
      - run: npm test
